#!/bin/bash
if [ $1 ] ; then
    TIMES=$1
else
    TIMES=10
fi

time for i in `seq $TIMES`
do
    # java -cp packed.jar testskummet.hello
    java -cp target/clojure-1.7.0-RC1-r4.jar:target-skummet testskummet.hello
done

