#!/bin/bash
mvn package
mkdir -p target-skummet
rm -rf target-skummet/*
java -cp target/clojure-1.7.0-skummet-SNAPSHOT.jar:. clojure.main test.clj
cp -r target/classes/clojure/asm target-skummet/clojure/
cp -r target/classes/clojure/lang target-skummet/clojure/
cp target/classes/clojure/version.properties target-skummet/clojure/
java -cp target-skummet testskummet.bar 123456 example
