#!/bin/bash
ARTIFACT=clojure
VERSION=1.7.0-RC1-r4

if [ $1 ] ; then
    TIMES=$1
else
    TIMES=10
fi

time for i in `seq $TIMES`
do
    # java -cp packed.jar testskummet.hello
    java -cp package/$ARTIFACT-$VERSION.jar:target testskummet.hello
done

